Repository ALLREVA/Allreva_BE, pull requests merged in 2024-12, with the labels that each got.

#63 [ARV-49] 차 대절 도메인 일부 구현
  src/main/java/com/backend/allreva/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/com/backend/allreva/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/backend/allreva/auth/exception/code/CustomAccessDeniedException.java
  src/main/java/com/backend/allreva/auth/exception/code/UnauthorizedException.java
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/java/com/backend/allreva/common/config/SecurityTestConfig.java
  src/main/java/com/backend/allreva/common/exception/CustomControllerAdvice.java
  src/main/java/com/backend/allreva/common/exception/CustomException.java
  src/main/java/com/backend/allreva/concert/command/domain/ConcertRepository.java
  src/main/java/com/backend/allreva/concert/infra/ConcertRepositoryImpl.java
  src/main/java/com/backend/allreva/rent/command/application/RentCommandService.java
  src/main/java/com/backend/allreva/rent/command/application/RentFormReadService.java
  src/main/java/com/backend/allreva/rent/command/application/RentFormWriteService.java
  src/main/java/com/backend/allreva/rent/command/application/dto/RentFormIdRequest.java
  src/main/java/com/backend/allreva/rent/command/application/dto/RentFormIdResponse.java
  src/main/java/com/backend/allreva/rent/command/application/dto/RentFormRegisterRequest.java
  src/main/java/com/backend/allreva/rent/command/application/dto/RentFormUpdateRequest.java
  src/main/java/com/backend/allreva/rent/command/domain/RentForm.java
  src/main/java/com/backend/allreva/rent/command/domain/RentFormBoardingDate.java
  src/main/java/com/backend/allreva/rent/command/domain/RentFormBoardingDateRepository.java
  src/main/java/com/backend/allreva/rent/command/domain/RentFormRepository.java
  src/main/java/com/backend/allreva/rent/command/domain/RentJoinRepository.java
  src/main/java/com/backend/allreva/rent/command/domain/value/AdditionalInfo.java
  src/main/java/com/backend/allreva/rent/command/domain/value/OperationInfo.java
  src/main/java/com/backend/allreva/rent/exception/RentErrorCode.java
  src/main/java/com/backend/allreva/rent/exception/RentFormAccessDeniedException.java
  src/main/java/com/backend/allreva/rent/exception/RentFormNotFoundException.java
  src/main/java/com/backend/allreva/rent/infra/RentFormQueryRepositoryImpl.java
  src/main/java/com/backend/allreva/rent/query/application/RentFormQueryRepository.java
  src/main/java/com/backend/allreva/rent/query/application/RentFormQueryService.java
  src/main/java/com/backend/allreva/rent/query/application/dto/DepositAccountResponse.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentFormDetailResponse.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentFormSummaryResponse.java
  src/main/java/com/backend/allreva/rent/ui/RentFormController.java
  src/main/java/com/backend/allreva/rent/ui/RentFormControllerImpl.java
  src/main/java/com/backend/allreva/rent/ui/RentFormViewController.java
  src/main/java/com/backend/allreva/rent/ui/RentFormViewControllerImpl.java
  src/test/java/com/backend/allreva/concert/fixture/ConcertFixture.java
  src/test/java/com/backend/allreva/concert/fixture/ConcertHallFixture.java
  src/test/java/com/backend/allreva/member/fixture/MemberFixture.java
  src/test/java/com/backend/allreva/member/integration/OAuth2RegisterIntegrationTest.java
  src/test/java/com/backend/allreva/rent/command/RentFormCloseTest.java
  src/test/java/com/backend/allreva/rent/command/RentFormRegisterTest.java
  src/test/java/com/backend/allreva/rent/command/RentFormUpdateTest.java
  src/test/java/com/backend/allreva/rent/domain/RentFormTest.java
  src/test/java/com/backend/allreva/rent/fixture/RentFormFixture.java
  src/test/java/com/backend/allreva/rent/fixture/RentFormRegisterRequestFixture.java
  src/test/java/com/backend/allreva/rent/fixture/RentFormUpdateRequestFixture.java
  src/test/java/com/backend/allreva/rent/infra/RentFormReadTest.java
  src/test/java/com/backend/allreva/rent/infra/RentFormWriteTest.java
  src/test/java/com/backend/allreva/rent/query/RentFormDetailReadTest.java
  src/test/java/com/backend/allreva/rent/query/RentFormSummaryReadTest.java
  src/test/java/com/backend/allreva/support/ApiTestSupport.java
  src/test/java/com/backend/allreva/support/ContextHolderTestUtil.java
  src/test/java/com/backend/allreva/support/DatabaseCleanUpUtil.java
  src/test/java/com/backend/allreva/support/IntegrationTestSupport.java
Labels: ✨ feat

#71 [ARV-66] 마이페이지 수요조사 API 구현 & 수요조사 API 리팩토링
  .gitignore
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertScheduler.java
  src/main/java/com/backend/allreva/concert/infra/ConcertJpaRepository.java
  src/main/java/com/backend/allreva/concert/infra/dto/ConcertDateInfoResponse.java
  src/main/java/com/backend/allreva/member/infra/MemberDetailRepositoryImpl.java
  src/main/java/com/backend/allreva/member/query/application/MemberDetailRepository.java
  src/main/java/com/backend/allreva/member/query/application/MemberQueryService.java
  src/main/java/com/backend/allreva/member/query/application/dto/MemberDetail.java
  src/main/java/com/backend/allreva/member/ui/MemberController.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyCommandRepository.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyCommandService.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyConverter.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyScheduler.java
  src/main/java/com/backend/allreva/survey/command/application/dto/JoinSurveyRequest.java
  src/main/java/com/backend/allreva/survey/command/application/dto/OpenSurveyRequest.java
  src/main/java/com/backend/allreva/survey/command/application/dto/SurveyIdRequest.java
  src/main/java/com/backend/allreva/survey/command/application/dto/SurveyIdResponse.java
  src/main/java/com/backend/allreva/survey/command/application/dto/SurveyJoinIdResponse.java
  src/main/java/com/backend/allreva/survey/command/application/dto/UpdateSurveyRequest.java
  src/main/java/com/backend/allreva/survey/command/domain/Survey.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyBoardingDate.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyBoardingDateCommandRepository.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyCommandRepository.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyJoin.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyJoinCommandRepository.java
  src/main/java/com/backend/allreva/survey/exception/SurveyErrorCode.java
  src/main/java/com/backend/allreva/survey/exception/SurveyInvalidBoardingDateException.java
  src/main/java/com/backend/allreva/survey/infra/MemberSurveyRepositoryImpl.java
  src/main/java/com/backend/allreva/survey/infra/SurveyQueryRepositoryImpl.java
  src/main/java/com/backend/allreva/survey/query/application/MemberSurveyQueryService.java
  src/main/java/com/backend/allreva/survey/query/application/SurveyQueryService.java
  src/main/java/com/backend/allreva/survey/query/application/domain/MemberSurveyRepository.java
  src/main/java/com/backend/allreva/survey/query/application/domain/SurveyQueryRepository.java
  src/main/java/com/backend/allreva/survey/query/application/dto/CreatedSurveyResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/JoinSurveyResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveyDetailResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveyResponse.java
  src/main/java/com/backend/allreva/survey/ui/SurveyController.java
  src/test/java/com/backend/allreva/support/IntegrationTestSupport.java
  src/test/java/com/backend/allreva/survey/command/application/SurveyCommandIntegrationTest.java
  src/test/java/com/backend/allreva/survey/query/application/MemberSurveyIntegrationTest.java
  src/test/java/com/backend/allreva/survey/query/application/SurveyQueryIntegrationTest.java
  src/test/java/com/backend/allreva/survey/ui/SurveyUITest.java
Labels: ✨ feat

#79 [ARV-100] 수요조사 변경사항 반영 리팩토링
  src/main/java/com/backend/allreva/survey/infra/SurveyQueryRepositoryImpl.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveyBoardingDateResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveyDetailResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveySummaryResponse.java
  src/test/java/com/backend/allreva/survey/query/application/SurveyQueryIntegrationTest.java
  src/test/java/com/backend/allreva/survey/ui/SurveyUITest.java
Labels: 🔨 refactor

#85 [ARV-106] CORS 설정
  src/main/java/com/backend/allreva/common/config/WebMvcConfig.java
Labels: 🔧 chore

#81 [ARV-104] Blue Green 무중단 배포
  .github/workflows/CICD.yml
  deploy.sh
  docker-compose.yml
  src/main/java/com/backend/allreva/common/controller/HealthCheckController.java
Labels: 🔧 chore

#95 [ARV-118] MemberController 수정
  src/main/java/com/backend/allreva/member/ui/MemberController.java
Labels: 🐛 fix

#96 [ARV-98] 차 대절 신청 도메인 구현 및 조회 쿼리 작성
  src/main/java/com/backend/allreva/common/util/DateHolder.java
  src/main/java/com/backend/allreva/common/util/SystemDateHolder.java
  src/main/java/com/backend/allreva/rent/command/application/RentCommandService.java
  src/main/java/com/backend/allreva/rent/command/application/dto/RentJoinApplyRequest.java
  src/main/java/com/backend/allreva/rent/command/application/dto/RentJoinIdRequest.java
  src/main/java/com/backend/allreva/rent/command/application/dto/RentJoinUpdateRequest.java
  src/main/java/com/backend/allreva/rent/command/domain/RentJoin.java
  src/main/java/com/backend/allreva/rent/command/domain/RentJoinRepository.java
  src/main/java/com/backend/allreva/rent/command/domain/RentRepository.java
  src/main/java/com/backend/allreva/rent/command/domain/value/Depositor.java
  src/main/java/com/backend/allreva/rent/exception/RentErrorCode.java
  src/main/java/com/backend/allreva/rent/exception/RentJoinAccessDeniedException.java
  src/main/java/com/backend/allreva/rent/exception/RentJoinNotFoundException.java
  src/main/java/com/backend/allreva/rent/infra/RentJoinRepositoryImpl.java
  src/main/java/com/backend/allreva/rent/infra/RentQueryRepositoryImpl.java
  src/main/java/com/backend/allreva/rent/query/application/RentQueryRepository.java
  src/main/java/com/backend/allreva/rent/query/application/RentQueryService.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentAdminDetailResponse.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentAdminJoinDetailResponse.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentAdminSummaryResponse.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentDetailResponse.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentJoinSummaryResponse.java
  src/main/java/com/backend/allreva/rent/query/application/dto/RentSummaryResponse.java
  src/main/java/com/backend/allreva/rent/ui/RentController.java
  src/main/java/com/backend/allreva/rent/ui/RentControllerSwagger.java
  src/main/java/com/backend/allreva/rent/ui/RentViewController.java
  src/main/java/com/backend/allreva/rent/ui/RentViewControllerSwagger.java
  src/main/java/com/backend/allreva/survey/infra/MemberSurveyRepositoryImpl.java
  src/test/java/com/backend/allreva/rent/command/RentJoinApplyTest.java
  src/test/java/com/backend/allreva/rent/command/RentJoinDeleteTest.java
  src/test/java/com/backend/allreva/rent/command/RentJoinUpdateTest.java
  src/test/java/com/backend/allreva/rent/command/RentRegisterTest.java
  src/test/java/com/backend/allreva/rent/fixture/RentJoinApplyRequestFixture.java
  src/test/java/com/backend/allreva/rent/fixture/RentJoinFixture.java
  src/test/java/com/backend/allreva/rent/fixture/RentJoinUpdateRequestFixture.java
  src/test/java/com/backend/allreva/rent/infra/RentJoinReadTest.java
  src/test/java/com/backend/allreva/rent/infra/RentJoinWriteTest.java
  src/test/java/com/backend/allreva/rent/infra/RentReadTest.java
  src/test/java/com/backend/allreva/rent/query/RentAdminPageTest.java
  src/test/java/com/backend/allreva/rent/query/RentDetailReadTest.java
  src/test/java/com/backend/allreva/rent/query/RentJoinPageTest.java
  src/test/java/com/backend/allreva/rent/query/RentMainPageTest.java
  src/test/java/com/backend/allreva/rent/query/RentSummaryReadTest.java
  src/test/java/com/backend/allreva/support/FixedDateHolder.java
Labels: ✨ feat

#103 [ARV-124] Kopis Concert 정보 받아오는 API 호출 방식 변경
  src/main/java/com/backend/allreva/common/converter/DataConverter.java
  src/main/java/com/backend/allreva/common/converter/DateConverter.java
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertScheduler.java
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertService.java
  src/main/java/com/backend/allreva/concert/infra/dto/KopisConcertResponse.java
  src/main/java/com/backend/allreva/concert/ui/AdminConcertController.java
Labels: 🐛 fix, 🔨 refactor

#106 [ARV-120] OAuth2 로그인 리다이렉트 추가
  .gitignore
  build.gradle
  src/main/java/com/backend/allreva/artist/command/ArtistCommandService.java
  src/main/java/com/backend/allreva/auth/domain/RefreshToken.java
  src/main/java/com/backend/allreva/auth/domain/RefreshTokenRepository.java
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/allreva/auth/ui/OAuth2Controller.java
  src/main/java/com/backend/allreva/auth/ui/OAuth2ControllerSwagger.java
  src/main/java/com/backend/allreva/auth/util/CookieUtil.java
  src/main/java/com/backend/allreva/common/config/RedisEmbeddedConfig.java
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/java/com/backend/allreva/member/command/application/MemberArtistCommandService.java
  src/main/java/com/backend/allreva/member/command/application/MemberCommandFacade.java
  src/main/java/com/backend/allreva/member/command/application/MemberInfoCommandService.java
  src/main/java/com/backend/allreva/member/command/application/dto/MemberArtistRequest.java
  src/main/java/com/backend/allreva/member/command/application/dto/MemberInfoRequest.java
  src/main/java/com/backend/allreva/member/command/domain/MemberArtistService.java
  src/main/java/com/backend/allreva/member/ui/MemberController.java
  src/main/java/com/backend/allreva/member/ui/MemberControllerSwagger.java
  src/main/java/com/backend/allreva/member/ui/MemberViewController.java
  src/main/java/com/backend/allreva/member/ui/MemberViewControllerSwagger.java
  src/test/java/com/backend/allreva/artist/command/ArtistCommandServiceTest.java
  src/test/java/com/backend/allreva/member/command/MemberArtistCommandTest.java
  src/test/java/com/backend/allreva/member/command/MemberInfoCommandTest.java
  src/test/java/com/backend/allreva/member/integration/OAuth2RegisterIntegrationTest.java
  src/test/java/com/backend/allreva/member/ui/OAuth2RegisterUITest.java
Labels: 🐛 fix, 🔨 refactor

#110 [ARV-132] OAuth2 리다이렉트 급하게 수정
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: 🐛 fix

#107 [ARV-126] 차 대절 이벤트 발행 로직 구현
  src/main/java/com/backend/allreva/common/config/KafkaConfig.java
  src/main/java/com/backend/allreva/concert/command/domain/Concert.java
  src/main/java/com/backend/allreva/concert/command/domain/ViewAddedEvent.java
  src/main/java/com/backend/allreva/concert/infra/ConcertInternalEventHandler.java
  src/main/java/com/backend/allreva/rent/command/application/RentCommandService.java
  src/main/java/com/backend/allreva/rent/command/domain/Rent.java
  src/main/java/com/backend/allreva/rent/command/domain/RentDeleteEvent.java
  src/main/java/com/backend/allreva/rent/command/domain/RentSaveEvent.java
  src/main/java/com/backend/allreva/rent/infra/RentInternalEventHandler.java
  src/main/java/com/backend/allreva/rent/infra/RentListener.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyCommandService.java
  src/main/java/com/backend/allreva/survey/command/domain/Survey.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyDeletedEvent.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyJoinEvent.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveySavedEvent.java
  src/main/java/com/backend/allreva/survey/infra/SurveyInternalEventHandler.java
  src/main/java/com/backend/allreva/survey/infra/SurveyListener.java
Labels: ✨ feat

#108 [ARV-122] 인기 검색어 조회 API 구현
  .github/workflows/CICD.yml
  deploy.sh
  docker-compose.yml
  src/main/java/com/backend/allreva/common/config/RedisConfig.java
  src/main/java/com/backend/allreva/common/config/RedisEmbeddedConfig.java
  src/main/java/com/backend/allreva/search/command/PopularKeywordCommandService.java
  src/main/java/com/backend/allreva/search/command/PopularKeywordScheduler.java
  src/main/java/com/backend/allreva/search/infra/PopularKeywordRepository.java
  src/main/java/com/backend/allreva/search/infra/PopularKeywordRepositoryImpl.java
  src/main/java/com/backend/allreva/search/query/application/PopularKeywordQueryService.java
  src/main/java/com/backend/allreva/search/query/application/dto/ChangeStatus.java
  src/main/java/com/backend/allreva/search/query/application/dto/PopularKeywordResponse.java
  src/main/java/com/backend/allreva/search/query/application/dto/PopularKeywordResponses.java
  src/main/java/com/backend/allreva/search/ui/PopularKeywordController.java
  src/main/java/com/backend/allreva/seatReview/command/domain/SeatReview.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyCommandService.java
  src/main/java/com/backend/allreva/survey/command/domain/Survey.java
  src/main/java/com/backend/allreva/survey/infra/MemberSurveyRepositoryImpl.java
  src/main/java/com/backend/allreva/survey/infra/SurveyQueryRepositoryImpl.java
  src/main/java/com/backend/allreva/survey/query/application/dto/CreatedSurveyResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/JoinSurveyResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveyBoardingDateResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveyResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveySummaryResponse.java
  src/test/java/com/backend/allreva/search/command/PopularKeywordCommandTest.java
Labels: ✨ feat

#114 [ARV-133] Cookie가 인식되지 않은 문제 수정
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/allreva/auth/util/CookieUtil.java
Labels: 🐛 fix

#117 [ARV-136] Https 설정에 따른 SwaggerConfig 변경
  src/main/java/com/backend/allreva/common/config/SwaggerConfig.java
Labels: 🐛 fix

#119 [ARV-137] 토큰 Secure Cookie 적용
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/allreva/auth/util/CookieUtil.java
Labels: 🐛 fix

#122 [ARV-138] 쿠키 Cross Site 정책 적용
  src/main/java/com/backend/allreva/auth/util/CookieUtil.java
Labels: 🐛 fix

#123 [ARV-135] 토큰 검증 로직 및 redis 적용
  src/main/java/com/backend/allreva/auth/application/JwtService.java
  src/main/java/com/backend/allreva/auth/domain/RefreshToken.java
  src/main/java/com/backend/allreva/auth/domain/RefreshTokenRepository.java
  src/main/java/com/backend/allreva/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/com/backend/allreva/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/backend/allreva/auth/exception/JwtExceptionFilter.java
  src/main/java/com/backend/allreva/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/allreva/auth/util/JwtParser.java
  src/main/java/com/backend/allreva/auth/util/JwtProvider.java
  src/main/java/com/backend/allreva/auth/util/JwtValidator.java
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/java/com/backend/allreva/common/config/SecurityEndpointPaths.java
  src/main/java/com/backend/allreva/common/config/SwaggerConfig.java
  src/main/java/com/backend/allreva/common/util/CookieUtils.java
  src/main/java/com/backend/allreva/member/command/domain/MemberRepository.java
  src/main/java/com/backend/allreva/member/infra/MemberDetailRepositoryImpl.java
  src/main/java/com/backend/allreva/member/query/application/MemberQueryService.java
  src/main/java/com/backend/allreva/member/query/application/dto/NicknameDuplication.java
  src/main/java/com/backend/allreva/member/ui/MemberViewController.java
  src/main/java/com/backend/allreva/member/ui/MemberViewControllerSwagger.java
Labels: ✨ feat, 🐛 fix, 🔨 refactor

#134 [ARV-160] 토큰 인증 과정 단순화
  src/main/java/com/backend/allreva/auth/application/AuthService.java
  src/main/java/com/backend/allreva/auth/application/JwtService.java
  src/main/java/com/backend/allreva/auth/exception/code/ExpiredJwtTokenException.java
  src/main/java/com/backend/allreva/auth/exception/code/InvalidAccessTokenException.java
  src/main/java/com/backend/allreva/auth/exception/code/InvalidJwtSignatureException.java
  src/main/java/com/backend/allreva/auth/exception/code/InvalidJwtTokenException.java
  src/main/java/com/backend/allreva/auth/exception/code/InvalidRefreshTokenException.java
  src/main/java/com/backend/allreva/auth/exception/code/InvalidTokenException.java
  src/main/java/com/backend/allreva/auth/exception/code/JwtErrorCode.java
  src/main/java/com/backend/allreva/auth/exception/code/TokenNotFoundException.java
  src/main/java/com/backend/allreva/auth/exception/code/UnsupportedProviderException.java
  src/main/java/com/backend/allreva/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/auth/ui/AuthController.java
Labels: 🐛 fix

#143 [ARV-146] 차 대절 상세 조회 로직 개선
  src/main/java/com/backend/allreva/rent/command/application/RentCommandService.java
  src/main/java/com/backend/allreva/rent/command/application/request/RentIdRequest.java
  src/main/java/com/backend/allreva/rent/command/application/request/RentRegisterRequest.java
  src/main/java/com/backend/allreva/rent/command/application/request/RentUpdateRequest.java
  src/main/java/com/backend/allreva/rent/command/domain/RentRepository.java
  src/main/java/com/backend/allreva/rent/infra/rdb/RentDslRepositoryImpl.java
  src/main/java/com/backend/allreva/rent/infra/rdb/RentRepositoryImpl.java
  src/main/java/com/backend/allreva/rent/query/application/RentQueryRepository.java
  src/main/java/com/backend/allreva/rent/query/application/RentQueryService.java
  src/main/java/com/backend/allreva/rent/query/application/response/RentAdminDetailResponse.java
  src/main/java/com/backend/allreva/rent/query/application/response/RentAdminJoinDetailResponse.java
  src/main/java/com/backend/allreva/rent/query/application/response/RentAdminSummaryResponse.java
  src/main/java/com/backend/allreva/rent/query/application/response/RentDetailResponse.java
  src/main/java/com/backend/allreva/rent/query/application/response/RentJoinCountResponse.java
  src/main/java/com/backend/allreva/rent/query/application/response/RentJoinDetailResponse.java
  src/main/java/com/backend/allreva/rent/ui/RentController.java
  src/main/java/com/backend/allreva/rent/ui/RentControllerSwagger.java
  src/main/java/com/backend/allreva/rent/ui/RentSearchController.java
  src/main/java/com/backend/allreva/rent/ui/RentSearchControllerSwagger.java
  src/main/java/com/backend/allreva/rent/ui/RentViewController.java
  src/main/java/com/backend/allreva/rent/ui/RentViewControllerSwagger.java
  src/main/java/com/backend/allreva/rent_join/command/application/request/RentJoinApplyRequest.java
  src/main/java/com/backend/allreva/rent_join/command/application/request/RentJoinIdRequest.java
  src/main/java/com/backend/allreva/rent_join/command/application/request/RentJoinUpdateRequest.java
  src/main/java/com/backend/allreva/rent_join/command/domain/RentJoinRepository.java
  src/main/java/com/backend/allreva/rent_join/infra/RentJoinDslRepository.java
  src/main/java/com/backend/allreva/rent_join/infra/RentJoinRepositoryImpl.java
  src/main/java/com/backend/allreva/rent_join/query/RentJoinQueryService.java
  src/main/java/com/backend/allreva/rent_join/query/response/RentJoinResponse.java
  src/main/java/com/backend/allreva/rent_join/query/response/RentJoinSummaryResponse.java
  src/main/java/com/backend/allreva/rent_join/ui/RentJoinController.java
  src/main/java/com/backend/allreva/rent_join/ui/RentJoinControllerSwagger.java
  src/test/java/com/backend/allreva/rent/fixture/RentJoinApplyRequestFixture.java
  src/test/java/com/backend/allreva/rent/fixture/RentJoinUpdateRequestFixture.java
  src/test/java/com/backend/allreva/rent/integration/RentAdminPageTest.java
  src/test/java/com/backend/allreva/rent/integration/RentJoinPageTest.java
  src/test/java/com/backend/allreva/rent/integration/RentMainPageTest.java
Labels: 🐛 fix, 🔨 refactor

#147 [ARV-144] 검색어 증가 구현
  src/main/java/com/backend/allreva/concert/query/application/ConcertSearchService.java
Labels: ✨ feat

#150 [ARV-172] 토큰 재발급 이슈 수정
  src/main/java/com/backend/allreva/auth/security/JwtAuthenticationFilter.java
Labels: 🐛 fix

#152 [ARV-173] 권한 허용 URL 수정
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/java/com/backend/allreva/common/config/SecurityEndpointPaths.java
Labels: 🐛 fix
