Repository ALLREVA/Allreva_BE, pull requests merged in 2024-11, with the labels that each got.

#19 [ARV-13] Kopis API로 공연 정보 수집
  .gitignore
  build.gradle
  src/main/java/com/backend/allreva/AllrevaApplication.java
  src/main/java/com/backend/allreva/common/application/BaseEntity.java
  src/main/java/com/backend/allreva/common/converter/DataConverter.java
  src/main/java/com/backend/allreva/common/util/CsvUtil.java
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertScheduler.java
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertService.java
  src/main/java/com/backend/allreva/concert/command/application/KopisConcertService.java
  src/main/java/com/backend/allreva/concert/command/application/dto/KopisConcertResponse.java
  src/main/java/com/backend/allreva/concert/command/domain/Concert.java
  src/main/java/com/backend/allreva/concert/command/domain/ConcertRepository.java
  src/main/java/com/backend/allreva/concert/command/domain/value/ConcertInfo.java
  src/main/java/com/backend/allreva/concert/command/domain/value/ConcertStatus.java
  src/main/java/com/backend/allreva/concert/command/domain/value/IntroduceImage.java
  src/main/java/com/backend/allreva/concert/command/domain/value/Seller.java
  src/main/java/com/backend/allreva/concert/infra/KopisConcertServiceImpl.java
  src/main/java/com/backend/allreva/concert/infra/dto/Relate.java
  src/main/java/com/backend/allreva/concert/ui/AdminConcertController.java
  src/main/java/com/backend/allreva/hall/command/application/AdminHallService.java
  src/main/java/com/backend/allreva/hall/command/application/KopisHallService.java
  src/main/java/com/backend/allreva/hall/command/application/dto/KopisHallResponse.java
  src/main/java/com/backend/allreva/hall/command/domain/ConcertHall.java
  src/main/java/com/backend/allreva/hall/command/domain/ConcertHallRepository.java
  src/main/java/com/backend/allreva/hall/command/domain/value/ConcertHallInfo.java
  src/main/java/com/backend/allreva/hall/command/domain/value/ConvenienceInfo.java
  src/main/java/com/backend/allreva/hall/command/domain/value/Location.java
  src/main/java/com/backend/allreva/hall/infra/KopisHallServiceImpl.java
  src/main/java/com/backend/allreva/hall/infra/dto/Pfmplc.java
  src/main/java/com/backend/allreva/hall/ui/AdminHallController.java
  src/main/resources/kopis/performance_hall_list.csv
Labels: ✨ feat

#25 [ARV-19] 회원 기능 및 OAuth2 로그인 구현
  build.gradle
  src/main/java/com/backend/allreva/auth/application/AuthMember.java
  src/main/java/com/backend/allreva/auth/application/CustomUserDetailsService.java
  src/main/java/com/backend/allreva/auth/application/dto/PrincipalDetails.java
  src/main/java/com/backend/allreva/auth/application/dto/TokenResponse.java
  src/main/java/com/backend/allreva/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/com/backend/allreva/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/backend/allreva/auth/exception/code/ExpiredJwtTokenException.java
  src/main/java/com/backend/allreva/auth/exception/code/InvalidJwtSignatureException.java
  src/main/java/com/backend/allreva/auth/exception/code/InvalidJwtTokenException.java
  src/main/java/com/backend/allreva/auth/exception/code/JwtErrorCode.java
  src/main/java/com/backend/allreva/auth/exception/code/JwtTokenNotFoundException.java
  src/main/java/com/backend/allreva/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/auth/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/backend/allreva/auth/oauth2/application/dto/OAuth2UserInfo.java
  src/main/java/com/backend/allreva/auth/oauth2/exception/OAuth2ErrorCode.java
  src/main/java/com/backend/allreva/auth/oauth2/exception/UnsupportedProviderException.java
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/allreva/auth/util/JwtParser.java
  src/main/java/com/backend/allreva/auth/util/JwtProvider.java
  src/main/java/com/backend/allreva/auth/util/JwtValidator.java
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/java/com/backend/allreva/common/dto/Response.java
  src/main/java/com/backend/allreva/common/exception/code/GlobalErrorCode.java
  src/main/java/com/backend/allreva/common/model/Email.java
  src/main/java/com/backend/allreva/member/command/application/MemberCommandService.java
  src/main/java/com/backend/allreva/member/command/application/MemberRepository.java
  src/main/java/com/backend/allreva/member/command/application/dto/MemberOAuth2RegisterRequest.java
  src/main/java/com/backend/allreva/member/command/domain/LoginProvider.java
  src/main/java/com/backend/allreva/member/command/domain/Member.java
  src/main/java/com/backend/allreva/member/command/domain/MemberInfo.java
  src/main/java/com/backend/allreva/member/command/domain/MemberRole.java
  src/main/java/com/backend/allreva/member/ui/OAuth2RegisterController.java
Labels: ✨ feat, 🔧 chore

#27 [ARV-24] Artist, RentForm, Diary Entity 생성
  src/main/java/com/backend/allreva/artist/command/domain/Artist.java
  src/main/java/com/backend/allreva/auth/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/backend/allreva/auth/oauth2/application/dto/OAuth2UserInfo.java
  src/main/java/com/backend/allreva/common/model/Image.java
  src/main/java/com/backend/allreva/concert/command/application/dto/KopisConcertResponse.java
  src/main/java/com/backend/allreva/concert/command/domain/Concert.java
  src/main/java/com/backend/allreva/diary/command/domain/ConcertDiary.java
  src/main/java/com/backend/allreva/member/command/application/MemberRepository.java
  src/main/java/com/backend/allreva/member/command/domain/Member.java
  src/main/java/com/backend/allreva/member/command/domain/MemberArtist.java
  src/main/java/com/backend/allreva/member/command/domain/value/LoginProvider.java
  src/main/java/com/backend/allreva/member/command/domain/value/MemberInfo.java
  src/main/java/com/backend/allreva/member/command/domain/value/MemberRole.java
  src/main/java/com/backend/allreva/rent/command/domain/RentForm.java
  src/main/java/com/backend/allreva/rent/command/domain/RentJoin.java
  src/main/java/com/backend/allreva/rent/command/domain/value/AdditionalInfo.java
  src/main/java/com/backend/allreva/rent/command/domain/value/BoardingType.java
  src/main/java/com/backend/allreva/rent/command/domain/value/Bus.java
  src/main/java/com/backend/allreva/rent/command/domain/value/BusSize.java
  src/main/java/com/backend/allreva/rent/command/domain/value/BusType.java
  src/main/java/com/backend/allreva/rent/command/domain/value/Depositor.java
  src/main/java/com/backend/allreva/rent/command/domain/value/DetailInfo.java
  src/main/java/com/backend/allreva/rent/command/domain/value/OperationInfo.java
  src/main/java/com/backend/allreva/rent/command/domain/value/Price.java
  src/main/java/com/backend/allreva/rent/command/domain/value/RefundType.java
  src/main/java/com/backend/allreva/rent/command/domain/value/Region.java
Labels: ✨ feat

#26 [ARV-25] 엔티티 작성1
  src/main/java/com/backend/allreva/common/model/Image.java
  src/main/java/com/backend/allreva/seatReview/command/domain/SeatReview.java
  src/main/java/com/backend/allreva/seatReview/command/domain/SeatReviewLike.java
  src/main/java/com/backend/allreva/survey/command/domain/Survey.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyJoin.java
  src/main/java/com/backend/allreva/survey/command/domain/value/BoardingType.java
Labels: ✨ feat

#30 [ARV-26] dependency 교체 및 favicon 요청 처리
  build.gradle
  src/main/java/com/backend/allreva/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/common/application/S3ImageService.java
  src/main/java/com/backend/allreva/common/config/S3Config.java
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/resources/static/favicon.ico
Labels: 🔧 chore

#29 [ARV-12] Concert, ConcertHall 상세 조회 구현 완료
  build.gradle
  src/main/java/com/backend/allreva/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/common/config/QuerydslConfig.java
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/java/com/backend/allreva/common/model/Image.java
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertService.java
  src/main/java/com/backend/allreva/concert/command/application/dto/KopisConcertResponse.java
  src/main/java/com/backend/allreva/concert/command/domain/Concert.java
  src/main/java/com/backend/allreva/concert/command/domain/ConcertRepository.java
  src/main/java/com/backend/allreva/concert/command/domain/value/Code.java
  src/main/java/com/backend/allreva/concert/command/domain/value/ConcertInfo.java
  src/main/java/com/backend/allreva/concert/command/domain/value/DateInfo.java
  src/main/java/com/backend/allreva/concert/command/domain/value/Seller.java
  src/main/java/com/backend/allreva/concert/infra/ConcertRepositoryImpl.java
  src/main/java/com/backend/allreva/concert/query/application/ConcertQueryService.java
  src/main/java/com/backend/allreva/concert/query/application/ConcertRepositoryCustom.java
  src/main/java/com/backend/allreva/concert/query/application/dto/ConcertDetail.java
  src/main/java/com/backend/allreva/concert/query/application/dto/ConcertSummary.java
  src/main/java/com/backend/allreva/concert/ui/ConcertController.java
  src/main/java/com/backend/allreva/hall/command/application/dto/KopisHallResponse.java
  src/main/java/com/backend/allreva/hall/command/domain/ConcertHall.java
  src/main/java/com/backend/allreva/hall/command/domain/ConcertHallRepository.java
  src/main/java/com/backend/allreva/hall/command/domain/value/ConcertHallInfo.java
  src/main/java/com/backend/allreva/hall/command/domain/value/ConvenienceInfo.java
  src/main/java/com/backend/allreva/hall/command/domain/value/Location.java
  src/main/java/com/backend/allreva/hall/infra/ConcertHallRepositoryCustom.java
  src/main/java/com/backend/allreva/hall/infra/ConcertHallRepositoryImpl.java
  src/main/java/com/backend/allreva/hall/query/application/ConcertHallQueryService.java
  src/main/java/com/backend/allreva/hall/query/application/dto/ConcertHallDetail.java
  src/main/java/com/backend/allreva/hall/ui/ConcertHallController.java
  src/main/java/com/backend/allreva/member/exception/MemberErrorCode.java
Labels: ✨ feat

#34 [ARV-36] JWT Swagger 설정
  src/main/java/com/backend/allreva/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/com/backend/allreva/auth/util/JwtTestTokenInitializer.java
  src/main/java/com/backend/allreva/common/config/SwaggerConfig.java
  src/main/java/com/backend/allreva/common/runner/MemberDummyDataInitializer.java
Labels: ✨ feat

#38 [ARV-32] 프로필 편집 및 환불 계좌 구현
  src/main/java/com/backend/allreva/artist/command/ArtistCommandService.java
  src/main/java/com/backend/allreva/artist/command/ArtistRepository.java
  src/main/java/com/backend/allreva/artist/exception/ArtistErrorCode.java
  src/main/java/com/backend/allreva/artist/exception/ArtistNotFoundException.java
  src/main/java/com/backend/allreva/auth/application/CustomUserDetailsService.java
  src/main/java/com/backend/allreva/auth/application/dto/TokenResponse.java
  src/main/java/com/backend/allreva/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/com/backend/allreva/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/backend/allreva/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/auth/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/backend/allreva/auth/oauth2/application/dto/OAuth2UserInfo.java
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/allreva/auth/util/JwtParser.java
  src/main/java/com/backend/allreva/auth/util/JwtProvider.java
  src/main/java/com/backend/allreva/auth/util/JwtTestTokenInitializer.java
  src/main/java/com/backend/allreva/auth/util/JwtValidator.java
  src/main/java/com/backend/allreva/common/aop/log/LogAspect.java
  src/main/java/com/backend/allreva/common/aop/log/LogTracer.java
  src/main/java/com/backend/allreva/common/aop/log/TraceId.java
  src/main/java/com/backend/allreva/common/aop/log/TraceStatus.java
  src/main/java/com/backend/allreva/common/model/Email.java
  src/main/java/com/backend/allreva/common/runner/MemberDummyDataInitializer.java
  src/main/java/com/backend/allreva/member/command/application/MemberArtistCommandService.java
  src/main/java/com/backend/allreva/member/command/application/MemberCommandFacade.java
  src/main/java/com/backend/allreva/member/command/application/MemberCommandService.java
  src/main/java/com/backend/allreva/member/command/application/MemberInfoCommandService.java
  src/main/java/com/backend/allreva/member/command/application/dto/AddMemberRequest.java
  src/main/java/com/backend/allreva/member/command/application/dto/MemberInfoRequest.java
  src/main/java/com/backend/allreva/member/command/application/dto/MemberOAuth2RegisterRequest.java
  src/main/java/com/backend/allreva/member/command/application/dto/RefundAccountRequest.java
  src/main/java/com/backend/allreva/member/command/domain/Member.java
  src/main/java/com/backend/allreva/member/command/domain/MemberArtist.java
  src/main/java/com/backend/allreva/member/command/domain/MemberArtistRepository.java
  src/main/java/com/backend/allreva/member/command/domain/MemberArtistService.java
  src/main/java/com/backend/allreva/member/command/domain/MemberRepository.java
  src/main/java/com/backend/allreva/member/command/domain/value/MemberInfo.java
  src/main/java/com/backend/allreva/member/command/domain/value/RefundAccount.java
  src/main/java/com/backend/allreva/member/infra/MemberDetailRepositoryImpl.java
  src/main/java/com/backend/allreva/member/infra/MemberRepositoryCustom.java
  src/main/java/com/backend/allreva/member/infra/MemberRepositoryImpl.java
  src/main/java/com/backend/allreva/member/infra/converter/RefundAccountConverter.java
  src/main/java/com/backend/allreva/member/query/MemberDetail.java
  src/main/java/com/backend/allreva/member/query/MemberDetailRepository.java
  src/main/java/com/backend/allreva/member/query/application/MemberQueryService.java
  src/main/java/com/backend/allreva/member/ui/MemberController.java
  src/main/java/com/backend/allreva/member/ui/OAuth2Controller.java
  src/main/java/com/backend/allreva/member/ui/OAuth2RegisterController.java
  src/test/java/com/backend/allreva/AllrevaApplicationTests.java
  src/test/java/com/backend/allreva/member/command/MemberArtistCommandTest.java
  src/test/java/com/backend/allreva/member/command/MemberInfoCommandTest.java
  src/test/java/com/backend/allreva/member/command/RefundAccountCommandTest.java
  src/test/java/com/backend/allreva/member/integration/OAuth2RegisterIntegrationTest.java
  src/test/java/com/backend/allreva/member/ui/OAuth2RegisterUITest.java
  src/test/java/com/backend/allreva/support/ApiTestSupport.java
  src/test/java/com/backend/allreva/support/DatabaseCleanUpUtil.java
  src/test/java/com/backend/allreva/support/IntegrationTestSupport.java
Labels: ✨ feat

#42 [ARV-51] CORS 설정
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
Labels: 🐛 fix

#44 [ARV-53] JwtAuthenticationFilter 모든 요청 허용하도록 수정
  src/main/java/com/backend/allreva/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/com/backend/allreva/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/backend/allreva/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/auth/util/JwtValidator.java
  src/main/java/com/backend/allreva/common/exception/CustomControllerAdvice.java
Labels: 🐛 fix

#53 [ARV-57] Kopis API OpenFeign으로 받아오도록 변경
  build.gradle
  src/main/java/com/backend/allreva/AllrevaApplication.java
  src/main/java/com/backend/allreva/common/feign/OpenFeignClient.java
  src/main/java/com/backend/allreva/common/util/CsvUtil.java
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertScheduler.java
  src/main/java/com/backend/allreva/concert/command/application/AdminConcertService.java
  src/main/java/com/backend/allreva/concert/command/application/KopisConcertService.java
  src/main/java/com/backend/allreva/concert/command/application/dto/KopisConcertResponse.java
  src/main/java/com/backend/allreva/concert/command/domain/Concert.java
  src/main/java/com/backend/allreva/concert/infra/KopisConcertOpenFeignClient.java
  src/main/java/com/backend/allreva/concert/infra/KopisConcertServiceImpl.java
  src/main/java/com/backend/allreva/concert/infra/dto/KopisConcertCodeResponse.java
  src/main/java/com/backend/allreva/concert/infra/dto/KopisConcertResponse.java
  src/main/java/com/backend/allreva/concert/ui/AdminConcertController.java
  src/main/java/com/backend/allreva/hall/command/application/AdminHallService.java
  src/main/java/com/backend/allreva/hall/command/application/KopisHallService.java
  src/main/java/com/backend/allreva/hall/command/application/dto/KopisHallResponse.java
  src/main/java/com/backend/allreva/hall/infra/KopisHallOpenFeignClient.java
  src/main/java/com/backend/allreva/hall/infra/KopisHallServiceImpl.java
  src/main/java/com/backend/allreva/hall/infra/dto/KopisHallResponse.java
  src/main/java/com/backend/allreva/hall/infra/dto/Pfmplc.java
  src/main/java/com/backend/allreva/hall/ui/AdminHallController.java
  src/test/java/com/backend/allreva/ControllerTestSupport.java
  src/test/java/com/backend/allreva/IntegralTestSupport.java
  src/test/java/com/backend/allreva/concert/ConcertQueryTest.java
  src/test/java/com/backend/allreva/support/ApiTestSupport.java
  src/test/java/com/backend/allreva/support/IntegrationTestSupport.java
  src/test/java/com/backend/allreva/support/WithCustomMockUser.java
  src/test/java/com/backend/allreva/support/WithCustomMockUserSecurityContextFactory.java
  src/test/java/com/backend/allreva/survey/command/application/SurveyCommandServiceTest.java
  src/test/java/com/backend/allreva/survey/query/application/SurveyQueryServiceTest.java
  src/test/java/com/backend/allreva/survey/ui/SurveyControllerTest.java
Labels: 🔨 refactor

#59 [ARV-67] 테스트용 ADMIN 토근 발급 API 구현
  src/main/java/com/backend/allreva/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/backend/allreva/auth/filter/TestAuthenticationFilter.java
  src/main/java/com/backend/allreva/auth/ui/DeveloperTestHandler.java
  src/main/java/com/backend/allreva/auth/ui/OAuth2Controller.java
  src/main/java/com/backend/allreva/auth/util/JwtTestTokenInitializer.java
  src/main/java/com/backend/allreva/common/config/SecurityConfig.java
  src/main/java/com/backend/allreva/common/config/SecurityTestConfig.java
  src/main/java/com/backend/allreva/common/config/SwaggerConfig.java
  src/main/java/com/backend/allreva/common/runner/MemberDummyDataInitializer.java
  src/main/java/com/backend/allreva/member/command/domain/MemberRepository.java
  src/main/java/com/backend/allreva/member/command/domain/value/MemberRole.java
  src/test/java/com/backend/allreva/support/ApiTestSupport.java
Labels: 🐛 fix

#64 [ARV-83] 수요조사, 차대절 BoardingDate 엔티티 생성
  src/main/java/com/backend/allreva/rent/command/domain/RentFormBoardingDate.java
  src/main/java/com/backend/allreva/rent/command/domain/value/OperationInfo.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyBoardingDateCommandRepository.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyCommandService.java
  src/main/java/com/backend/allreva/survey/command/application/SurveyConverter.java
  src/main/java/com/backend/allreva/survey/command/application/dto/OpenSurveyRequest.java
  src/main/java/com/backend/allreva/survey/command/application/dto/UpdateSurveyRequest.java
  src/main/java/com/backend/allreva/survey/command/domain/Survey.java
  src/main/java/com/backend/allreva/survey/command/domain/SurveyBoardingDate.java
  src/main/java/com/backend/allreva/survey/infra/SurveyQueryRepositoryImpl.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveyDetailResponse.java
  src/main/java/com/backend/allreva/survey/query/application/dto/SurveySummaryResponse.java
  src/test/java/com/backend/allreva/survey/command/application/SurveyCommandServiceTest.java
  src/test/java/com/backend/allreva/survey/query/application/SurveyQueryServiceTest.java
  src/test/java/com/backend/allreva/survey/ui/SurveyControllerTest.java
Labels: 🔨 refactor
